import { Inter, Audiowide } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
const audiowide = Audiowide({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "todo-app-next",
  description: "Generated by Shadow",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
